-- stuff i'm stealing from kickstart :)
vim.keymap.set("n", 'gd', require('telescope.builtin').lsp_definitions)
vim.keymap.set("n", 'gr', require('telescope.builtin').lsp_references)
vim.keymap.set("n", 'gI', require('telescope.builtin').lsp_implementations)
vim.keymap.set("n", '<leader>D', require('telescope.builtin').lsp_type_definitions)
vim.keymap.set("n", '<leader>ds', require('telescope.builtin').lsp_document_symbols)
vim.keymap.set("n", '<leader>ws', require('telescope.builtin').lsp_dynamic_workspace_symbols)
vim.keymap.set("n", '<leader>rn', vim.lsp.buf.rename)
vim.keymap.set("n", '<leader>ca', vim.lsp.buf.code_action)
vim.keymap.set("n", 'gD', vim.lsp.buf.declaration)

